CDEFS += -DSERIAL0_BAUD=115200

include ../libraries/Serial/Makefile
include ../libraries/Circular/DumpCircular/Makefile
include ../libraries/packet/Makefile
include ../libraries/Wire/StateTwoWire/Makefile
include ../libraries/bmp180/Makefile
include ../libraries/mpu60x0/Makefile
include ../libraries/hmc5883/Makefile
include ../libraries/System/Makefile

