MEDIA=/media/blah

include ../libraries/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/gpio/Makefile
include ../libraries/Circular/Makefile
include ../libraries/System/Makefile


