LIBMAKE+=../libraries/Circular/DumpCircular/Makefile
#CPPSRC+=../libraries/PrintCircular/PrintCircular.cpp
EXTRAINCDIRS +=../libraries/Circular/DumpCircular/

include ../libraries/dump/Makefile
include ../libraries/Circular/Makefile


